model:
  name: "gpt2"  # or any other model supported by NIM
  max_length: 100
  temperature: 0.7
  top_p: 0.9

server:
  host: "0.0.0.0"
  port: 8000

adaptive_learning:
  fine_tuning:
    learning_rate: 5e-5
    num_train_epochs: 3
    per_device_train_batch_size: 8
  few_shot:
    max_examples: 5

monitoring:
  prometheus_port: 9090
